config/routes.rb
Wuzbest::Application.routes.draw do
  get "welcome/index"

  get "home/index"

  devise_for :users

  resources :users

  resources :questions

  resources :answers

  resources :comments

  resources :comparaisons

  resources :categories

  resources :shops

  resources :manufacturers

  resources :products

  root :to => 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :created_at, :parent_id, :updated_at, :user_id
  belongs_to :user_id
  has_and_belongs_to_many :questions

  validates :content, :presence => true , :length => {:minimum => 5}

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id, :slug
  has_many :products

end

app/models/cities_shop.rb
# encoding: utf-8 
class CitiesShop < ActiveRecord::Base 

  attr_accessible  :id, :name, :long_desc, :coord_lat, :coord_long, :main_shop_id, :web, :contact_phone, :contact_fax, :contact_email, :user_id, :slug, :shop, :shop_id

  belongs_to :shop 

  validates :slug, :presence => true

end

app/models/city.rb
# encoding: utf-8 
class City < ActiveRecord::Base 

  attr_accessible  :id, :name, :slug, :state, :state_id

  belongs_to :state

  validates :slug, :uniqueness => true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :created_at, :is_in_favor, :parent_id, :user_id
end

app/models/comparaison.rb
class Comparaison < ActiveRecord::Base
  attr_accessible :category_id, :created_at, :first_product_id, :second_product_id, :slug, :user_id
end

app/models/config.rb
# encoding: utf-8 
class Config < ActiveRecord::Base 

  attr_accessible  :id, :value_name, :value, :config_type, :config_type_id

  belongs_to :config_type 


end

app/models/config_type.rb
# encoding: utf-8 
class ConfigType < ActiveRecord::Base 

  attr_accessible  :id, :name, :slug

  has_many :configs, dependent: :destroy 

  validates :name, :presence => true
  validates :slug, :presence => true, :uniqueness => true

end

app/models/country.rb
# encoding: utf-8 
class Country < ActiveRecord::Base 

  attr_accessible  :id, :name, :languages, :ref, :coord_lat, :coord_long, :phone_prefix, :currency, :currency_id

  belongs_to :currency 
  has_many :states, dependent: :destroy 


end

app/models/currency.rb
# encoding: utf-8 
class Currency < ActiveRecord::Base 

  attr_accessible  :id, :ref, :value_to_usd

  has_many :countries, dependent: :destroy 

  validates :ref, :uniqueness => true

end

app/models/feedback.rb
# encoding: utf-8 
class Feedback < ActiveRecord::Base 

  attr_accessible  :id, :label, :content, :is_fixed, :user_id, :fixed_by_id, :fixed_at

  belongs_to :user, class_name: 'User' 
  belongs_to :fixed_by, class_name: 'User' 


end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  attr_accessible :adress, :city_id, :closed_at, :contact_email, :contact_fax, :contact_phone, :country_id, :cover_id, :created_at, :founded_at, :hq_lat, :hq_long, :long_desc, :name, :owner_id, :slug, :state_id, :stock_dir, :stock_ref, :stock_value, :updated_at, :user_id, :web
  has_many :products
  belongs_to :category

  # Composite primary key
  validates :id, :uniqueness => { :scope => [ :user_id , :category_id ] }
  validates :name, :presence => true, :uniqueness => true
  validates :long_desc, :length => { :minimum => 5 }

  validates :state_id , :city_id , :country_id, :presence => true , :allow_nil => false, :allow_blank => true
end

app/models/message.rb
# encoding: utf-8 
class Message < ActiveRecord::Base 

  attr_accessible  :id, :subject, :content, :is_seen, :sender_id, :reciever_id, :first_delete_id, :second_delete_id, :message, :message_id

  belongs_to :sender, class_name: 'User' 
  belongs_to :reciever, class_name: 'User' 
  belongs_to :first_delete, class_name: 'User' 
  belongs_to :second_delete, class_name: 'User' 
  has_and_belongs_to_many :messages 
  has_and_belongs_to_many :admin_contacts 


end

app/models/picture.rb
# encoding: utf-8 
class Picture < ActiveRecord::Base 

  attr_accessible  :id, :path, :mime_type, :uploaded_at, :label, :description, :file_size, :is_used, :width, :height, :xiff, :credentials, :is_highlighted

  has_many :users, dependent: :destroy 
  has_many :cities_pictures 
  has_many :countries, through: :cities_pictures 
  has_and_belongs_to_many :currencies 
  has_and_belongs_to_many :states 
  has_and_belongs_to_many :cities 
  has_many :board_folders, dependent: :destroy 
  has_many :pictures_users 
  has_many :users, through: :pictures_users 


end

app/models/post.rb
# encoding: utf-8 
class Post < ActiveRecord::Base 

  attr_accessible  :id, :title, :content, :user, :user_id, :score, :type

  belongs_to :user 
  has_and_belongs_to_many :comments 


end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :brag_id, :created_at, :long_desc, :manufacturer_id, :name, :original_product_id, :refname, :released_at, :slug, :updated_at
has_many :specifications
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :created_at, :status, :user_id
  has_many :answers
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :city_id, :contact_email, :contact_fax, :contact_phone, :main_shop_id, :slug, :state_id, :user_id, :web

  has_many :products
end

app/models/state.rb
# encoding: utf-8 
class State < ActiveRecord::Base 

  attr_accessible  :id, :name, :slug, :country, :country_id

  belongs_to :country 
  has_many :cities, dependent: :destroy 

  validates :slug, :uniqueness => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :city_id, :confirmation_token, :country_id, :credentials_expire_at, :credentials_expired, :currency_id, :email, :email_canonical, :enabled, :expired, :expires_at, :last_login, :locked, :password, :password_requested_at, :roles, :salt, :state_id, :username, :username_canonical
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :main_shop_id %><br />
    <%= f.number_field :main_shop_id %>
  </div>
  <div class="field">
    <%= f.label :web %><br />
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br />
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_fax %><br />
    <%= f.text_field :contact_fax %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
    <%= f.number_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br />
    <%= f.text_field :city_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing shops</h1>

<table>
  <tr>
    <th>Main shop</th>
    <th>Web</th>
    <th>Contact phone</th>
    <th>Contact fax</th>
    <th>Contact email</th>
    <th>User</th>
    <th>Slug</th>
    <th>State</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= shop.main_shop_id %></td>
    <td><%= shop.web %></td>
    <td><%= shop.contact_phone %></td>
    <td><%= shop.contact_fax %></td>
    <td><%= shop.contact_email %></td>
    <td><%= shop.user_id %></td>
    <td><%= shop.slug %></td>
    <td><%= shop.state_id %></td>
    <td><%= shop.city_id %></td>
    <td><%= link_to 'Show', shop %></td>
    <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
    <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Main shop:</b>
  <%= @shop.main_shop_id %>
</p>

<p>
  <b>Web:</b>
  <%= @shop.web %>
</p>

<p>
  <b>Contact phone:</b>
  <%= @shop.contact_phone %>
</p>

<p>
  <b>Contact fax:</b>
  <%= @shop.contact_fax %>
</p>

<p>
  <b>Contact email:</b>
  <%= @shop.contact_email %>
</p>

<p>
  <b>User:</b>
  <%= @shop.user_id %>
</p>

<p>
  <b>Slug:</b>
  <%= @shop.slug %>
</p>

<p>
  <b>State:</b>
  <%= @shop.state_id %>
</p>

<p>
  <b>City:</b>
  <%= @shop.city_id %>
</p>


<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>